// Generated by https://quicktype.io

export interface EditPatientByIDResponse {
    id: string;
    name: string;
    lastName: string;
    birthDate: string;
    dni: string;
    email: string;
    phoneNumber: string;
    fotoUrl: string;
}
