export interface LoginResponse {
  id: string;
  mail: string;
  avatar: string;
  fullName: string;
  createdAt: string;
  token: string;
}

// Generated by https://quicktype.io

export interface RegisterResponse {
  id: string;
  mail: string;
  avatar: null;
  fullName: string;
  createdAt: string;
}