// Generated by https://quicktype.io



export interface patientBasicDataResponse {
    id: string;
    name: string;
    lastName: string;
    birthDate: string;
    dni: string;
    email: string;
}

