// Generated by https://quicktype.io

export interface SanitaryDetailsResponse {
    img:         string;
    fullname:    string;
    email:       string;
    phoneNumber: string;
    dni:         string;
    birthDate:   string;
}
